# Generated by Django 4.1.2 on 2022-11-01 07:57

import FilmyApp.app
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=500)),
                ('Experience', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=150)),
                ('file', FilmyApp.app.ContentTypeRestrictedFileField(upload_to='pdf')),
                ('Term_check', models.BooleanField()),
            ],
        ),
    ]
