# Generated by Django 4.1.2 on 2023-01-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
