# Generated by Django 4.1.2 on 2023-01-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0003_imageuploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdata',
            name='Name',
        ),
    ]
