# Generated by Django 4.1.2 on 2023-01-10 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0004_remove_contactdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 15, 50, 1, 358239)),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='FirstName',
            field=models.CharField(default='fname', max_length=100),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='LastName',
            field=models.CharField(default='lname', max_length=100),
        ),
    ]
