# Generated by Django 4.1.2 on 2023-01-10 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0005_contactdata_date_contactdata_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 18, 1, 2, 137994)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
    ]
