# Generated by Django 4.1.2 on 2023-01-11 04:18

import FilmyApp.app
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0006_alter_contactdata_date_alter_contactdata_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=400)),
                ('file', FilmyApp.app.ContentTypeRestrictedFileField(upload_to='pdf')),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 9, 48, 51, 935923)),
        ),
    ]
