# Generated by Django 4.1.2 on 2023-01-11 04:57

import FilmyApp.app
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0007_ideas_alter_contactdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Brand_Agency', models.CharField(max_length=100)),
                ('Industry', models.CharField(max_length=100)),
                ('Collaboration_Type', models.CharField(max_length=25)),
                ('file', FilmyApp.app.ContentTypeRestrictedFileField(upload_to='pdf')),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 10, 27, 22, 347495)),
        ),
    ]
