# Generated by Django 4.1.2 on 2023-01-11 05:57

import FilmyApp.app
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0009_collaboration_date_ideas_date_alter_contactdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Brand_Agency', models.CharField(max_length=35)),
                ('Industry', models.CharField(max_length=30)),
                ('Kind_Sponcer', models.CharField(max_length=30)),
                ('Sponcer_Type', models.CharField(max_length=30)),
                ('file', FilmyApp.app.ContentTypeRestrictedFileField(upload_to='pdf')),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 11, 27, 14, 915173))),
            ],
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 11, 27, 14, 915173)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 11, 27, 14, 915173)),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 11, 27, 14, 915173)),
        ),
    ]
