# Generated by Django 4.1.2 on 2023-02-21 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0010_sponsorship_alter_collaboration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Message',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Term_check',
        ),
        migrations.AddField(
            model_name='application',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 13, 4, 42, 14161)),
        ),
        migrations.AddField(
            model_name='application',
            name='FirstName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='LastName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 13, 4, 42, 14161)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 13, 4, 42, 14161)),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 13, 4, 42, 14161)),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 13, 4, 42, 14161)),
        ),
    ]
