# Generated by Django 5.1.4 on 2024-12-12 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0016_category_image_alter_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 15, 40, 53, 724247)),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 15, 40, 53, 739908)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 15, 40, 53, 724247)),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 15, 40, 53, 739908)),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 15, 40, 53, 739908)),
        ),
    ]
