# Generated by Django 5.1.4 on 2024-12-12 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyApp', '0017_galleryimage_is_main_alter_application_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='application',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 55, 22, 239324)),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 55, 22, 239324)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 55, 22, 239324)),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 55, 22, 239324)),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 55, 22, 239324)),
        ),
    ]
